name: build
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    types:
      - closed
      - opened
      - reopened
      - synchronize
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      affectedPackages: ${{ steps.get-affected-packages.outputs.packages }}
    if: "!(github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false)"
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Get affected packages
        id: get-affected-packages
        run: echo "packages=$(pnpm exec foundation-get-affected-project-chunks test:js origin/${{github.base_ref}} 4)" >> $GITHUB_OUTPUT

      - name: Compile source files
        run: pnpm run build

      - name: Lint affected source files
        run: pnpm run lint --filter=[origin/${{github.base_ref}}]

      - name: Get current git commit hash
        id: get-git-commit-hash
        run: |
          echo "gitCommitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  test-package:
    name: Test package
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.outputs.affectedPackages != '[]' }}
    strategy:
      matrix:
        packages: ${{fromJSON(needs.build.outputs.affectedPackages)}}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Get current git commit hash
        id: get-git-commit-hash
        run: |
          echo "gitCommitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Launch Unit Tests
        run: pnpm run test:unit:js --filter ${{ join(matrix.packages, ' --filter ') }}

      - name: Launch Integration Tests
        run: pnpm run test:integration:js --filter ${{ join(matrix.packages, ' --filter ') }}

  test-e2e:
    name: Run E2E tests.
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Run e2e tests (CJS)
        run: pnpm run test:e2e:cjs

      - name: Run e2e tests (ESM)
        run: pnpm run test:e2e:esm

  done:
    name: Done
    needs:
      - test-e2e
      - test-package
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Done!"'
